[build]
  publish = "public"
  command = "gatsby build"

[build.environment]
  YARN_VERSION = "1.10.1"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "https://florian-codes.netlify.com/*"
  to = "https://florian.codes/:splat"
  status = 301
  force = true
